### PR TITLE
Fixed Latvia and Lithuania zone files

### PR DESCRIPTION
**Pull request by dariuszz123**
Moved Latvia (lv) and Lithuania (lt) zones to corresponding zone files

### CODE REVIEW

**Comment by bojanz** [comment]
You fixed the names of the zones, but the zone members don't match the parents (LT has a LV zone member, and vice-versa).

**Comment by dariuszz123** [comment]
Oh... My bad, fixed that.

**Comment by bojanz** [comment]
Great! Pleae rebase into 1 commit, and I'll merge.

**Comment by dariuszz123** [comment]
Done.

**Comment by bojanz** [comment]
Thanks!

**Pull request merged**
