### PR TITLE
Added Canarian (Canary Islands) tax type and zone.

### PR DESCRIPTION
**Pull request by alle**

### CODE REVIEW

**Comment by bojanz** [comment]
What's going on here? 19 commits, merges, taxes for multiple countries?

**Comment by alle** [comment]
I'm a bit confused: my "original" PR was only for adding the Canarian taxes.

**Comment by bojanz** [comment]
You created a PR from your master, not from a branch, that's why. So it keeps reflecting the code you push to master.

**Comment by alle** [comment]
Yes, I realized that just after sending my previous comment.

**Pull request closed without merging**
